# This is a basic workflow to help you get started with Actions

name: CI-Share-Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains banana testing job
  sonarqube:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run "danger" script
        run: echo Mock danger

      - name: check-git-changes
        run: echo Mock check-git-changes

      - name: reconcile-config-check
        run: echo Mock reconcile-config-check

      - name: sonarqube
        run: echo Mock sonarqube
        
  storybook:
    # needs: [install-root, install-common, install-server, install-webapp]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install-xxx
        run: |
          npm install
          npm install --prefix packages/common
          npm install --prefix packages/server
          npm install --prefix packages/webapp

      - name: storybook-steps
        run: |
          echo Mock install-root
          echo Mock install-common
          echo Mock install-server
          echo Mock install-webapp
          echo Mock build-storybook
          echo Mock s3-publish-storybook

  static-checks:
    # needs: [sonarqube]
    # needs: [sonarqube, install-root, install-common, install-server, install-webapp]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: static-checks
        run: |
          echo Mock install-root
          echo Mock install-common
          echo Mock install-server
          echo Mock install-webapp
          echo Mock flow-common
          echo Mock lint-common
          echo Mock flow-server
          echo Mock lint-server
          echo Mock flow-webapp
          echo Mock lint-webapp
          echo Mock test-server
          echo Mock test-webapp
        
  build:
    # needs: [install-root, install-common, install-server, install-webapp]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install
        run: |
          echo Mock install-root
          echo Mock install-common
          echo Mock install-server
          echo Mock install-webapp

      - name: build-server
        run: |
          echo Mock build-server
          mkdir -p packages/server/build
          echo someServerArtifact > packages/server/build/serverArtifact.txt

      - name: build-webapp
        run: |
          echo Mock build-webapp
          mkdir -p packages/webapp/build
          echo someAppArtifact > packages/webapp/build/appArtifact.txt
    
      # upload
      - name: upload build-server artifact
        uses: actions/upload-artifact@master
        with:
          name: build-server-artifact
          path: packages/server/build
    
      # upload
      - name: upload build-webapp artifact
        uses: actions/upload-artifact@master
        with:
          name: build-webapp-artifact
          path: packages/webapp/build
        
  main:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # download
      - uses: actions/download-artifact@master
        with:
          name: build-webapp-artifact
          path: packages/webapp/build

      - name: check artifact
        run: |
          echo current directory:
          ls
          echo Read buildArtifact:
          cat packages/webapp/build/appArtifact.txt

      - name: steps after build
        run: |
          echo Mock bundlesize
          echo Mock fetch-translations
          echo Mock generate-translated-routes
          echo Mock build-translations
          echo Mock skyscanner-api-gateway-tallyman
          echo Mock skyscanner-api-gateway-banana
        
  lighthouse:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: check artifact
        run: |
          echo current directory:
          ls

      - name: lighthouse-steps
        run: |
          echo Mock create-cypress-lighthouse-reports-dir
          echo Mock cypress-wait-for-server
          echo Mock cypress-lighthouse-homepage
          echo Mock cypress-lighthouse-combined-results
          echo Mock cypress-lighthouse-reports-comment
          echo Mock cypress-perf-upload
        
  cypress-acceptance_a11y_e2e:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: check artifact
        run: |
          echo current directory:
          ls

      - name: acceptance-tests
        run: |
          echo Mock npm-auth-acceptance-tests-cypress-folder
          echo Mock install-acceptance-tests-cypress
          echo Mock cypress-wait-for-server
          echo Mock lint-acceptance-tests-cypress
          echo Mock cypress-a11y
          echo Mock cypress-e2e
          echo Mock cypress-perf-upload
        
  cypress-gb_ru:
    needs: [build]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: check artifact
        run: |
          echo current directory:
          ls

      - name: cypress-steps
        run: |
          echo Mock create-cypress-lighthouse-reports-dir
          echo Mock cypress-wait-for-server
          echo Mock cypress-lighthouse-homepage
          echo Mock cypress-lighthouse-combined-results
          echo Mock cypress-lighthouse-reports-comment
          echo Mock cypress-perf-upload

